Repository Veloera/Veloera, pull requests merged in 2025-05, with the labels that each got.

#47 chore: fix typo
  web/src/pages/Channel/EditChannel.js
Labels: component: frontend, size:XS, lgtm

#61 Add option to hide upstream error details
  service/error.go
  setting/model_setting/global.go
  web/src/components/ModelSetting.js
  web/src/pages/Setting/Model/SettingGlobalModel.js
Labels: trige: enhancement, component: frontend, component: backend, size:S, codex

#49 添加新的拉新返佣功能
  common/constants.go
  controller/topup.go
  model/option.go
  model/redemption.go
  model/user.go
  web/src/components/OperationSetting.js
  web/src/pages/Setting/Operation/SettingsRebate.js
Labels: trige: feature, component: frontend, component: backend, size:L

#63 fix pop-ups blocked issuse
  web/src/components/utils.js
Labels: triage: bug, component: frontend, size:S
