Repository Veloera/Veloera, pull requests merged in 2025-09, with the labels that each got.

#195 fix(convert.go): fix Claude Code support (#190)
  service/convert.go
Labels: triage: bug, size:M, lgtm

#199 refactor: 重构模型映射逻辑及相关组件集成
  web/src/components/shared/ModelMappingEditor.js
  web/src/hooks/useModelMapping.js
  web/src/pages/Channel/EditChannel.js
  web/src/pages/Channel/EditTagModal.js
  web/src/utils/modelMappingUtils.js
Labels: trige: feature, component: frontend, size:XXL, lgtm

#205 feat: 增加IP显示
  web/src/components/LogsTable.js
Labels: trige: feature, size:M, lgtm

#226 feat: 添加 Gemini 格式兼容支持 (feat/gemini-format-compat)
  controller/gemini.go
  controller/relay.go
  dto/gemini_compat.go
  middleware/auth.go
  middleware/distributor.go
  relay/channel/gemini/relay-gemini.go
  relay/common/relay_info.go
  relay/constant/relay_mode.go
  router/relay-router.go
  service/gemini_compat.go
Labels: trige: feature, size:XL
