Repository Veloera/Veloera, pull requests merged in 2025-07, with the labels that each got.

#125 [Snyk] Upgrade @visactor/react-vchart from 1.8.11 to 1.13.11
  web/package.json
Labels: component: frontend, size:XS

#134 feat(inbox-system): add comprehensive design, requirements, and imple…
  .gitignore
  .kiro/specs/inbox-system/design.md
  .kiro/specs/inbox-system/requirements.md
  .kiro/specs/inbox-system/tasks.md
  controller/message.go
  dto/message.go
  model/main.go
  model/message.go
  router/api-router.go
  web/src/App.js
  web/src/components/AdminRoute.js
  web/src/components/HeaderBar.js
  web/src/components/InboxIcon.js
  web/src/components/SiderBar.js
  web/src/pages/Inbox/MessageDetail.js
  web/src/pages/Inbox/index.js
  web/src/pages/Message/CreateMessage.js
  web/src/pages/Message/EditMessage.js
  web/src/pages/Message/MessageList.js
  web/src/pages/Message/index.js
Labels: trige: feature, size:XXL

#138 fix: 修复因消息内容为空导致测试和接入gemini之后请求失败的问题
  relay/channel/gemini/relay-gemini.go
Labels: triage: bug, component: backend, size:XS, lgtm

#129 feat: support -thinking-{budget} to set budget tokens
  relay/channel/gemini/relay-gemini.go
  setting/model_setting/gemini.go
  web/src/pages/Setting/Model/SettingGeminiModel.js
Labels: trige: feature, size:M

#142 feat: implement minimum trust level check
  common/constants.go
  controller/linuxdo.go
  controller/misc.go
  model/option.go
  web/src/components/SystemSetting.js
Labels: trige: feature, size:M, lgtm

#148 enhancement: 智谱渠道优化；修复侧边栏异常
  common/constants.go
  relay/channel/zhipu/adaptor.go
  relay/channel/zhipu/constants.go
  relay/channel/zhipu/dto.go
  relay/channel/zhipu/relay-zhipu.go
  relay/channel/zhipu_4v/adaptor.go
  relay/channel/zhipu_4v/constants.go
  relay/channel/zhipu_4v/dto.go
  relay/channel/zhipu_4v/relay-zhipu_v4.go
  relay/constant/api_type.go
  relay/relay_adaptor.go
  setting/operation_setting/model-ratio.go
  web/src/components/SiderBar.js
  web/src/constants/channel.constants.js
  web/src/index.css
Labels: trige: enhancement, size:XL
