Repository Veloera/Veloera, pull requests merged in 2025-06, with the labels that each got.

#67 fix: fetch_models use wrong apiKey and release.yml cache invalid
  .github/workflows/release.yml
  controller/channel.go
  web/src/pages/Channel/EditChannel.js
Labels: triage: bug, component: frontend, component: backend, size:L

#66 fix: wrongly add ThinkingConfig to normal models
  relay/channel/gemini/relay-gemini.go
  setting/model_setting/gemini.go
  web/src/components/ModelSetting.js
  web/src/pages/Setting/Model/SettingGeminiModel.js
Labels: triage: bug, size:M

#77 Update prefix cache after channel changes
  controller/channel.go
  middleware/distributor.go
Labels: component: backend, size:M, codex

#79 Fix schema cleaning
  relay/channel/gemini/relay-gemini.go
Labels: component: backend, size:L, codex

#80 feat:增强Gemini中继以支持Thought(思考过程)处理
  relay/channel/gemini/dto.go
  relay/channel/gemini/relay-gemini.go
Labels: trige: enhancement, size:S

#88 Fix: Prevent multiple redemptions of the same code under high concurr…
  controller/user.go
  model/redemption.go
Labels: size:S

#91 Add plugin block switch
  controller/relay.go
  setting/model_setting/global.go
  web/src/components/ModelSetting.js
  web/src/pages/Setting/Model/SettingGlobalModel.js
Labels: component: frontend, component: backend, size:M, codex

#95 Add stream_support pseudo streaming
  constant/channel_setting.go
  new-api-stuffs/docs/channel/other_setting.md
  relay/channel/gemini/relay-gemini.go
  relay/channel/openai/relay-openai.go
  relay/helper/common.go
  relay/relay-text.go
Labels: trige: enhancement, size:L, codex

#96 Fix Gemini pseudo stream parameter
  relay/channel/gemini/relay-gemini.go
Labels: size:XS, codex

#101 [Snyk] Upgrade lucide-react from 0.503.0 to 0.511.0
  web_v2/package.json
Labels: component: frontend, size:XS

#111 Add token rate limit feature
  controller/token.go
  middleware/auth.go
  middleware/token-rate-limit.go
  model/token.go
  router/relay-router.go
  web/src/i18n/locales/en.json
  web/src/pages/Token/EditToken.js
Labels: trige: feature, component: frontend, component: backend, size:L, lgtm, codex

#112 feat: implement error logging
  common/constants.go
  common/logger.go
  controller/relay.go
  model/log.go
  model/option.go
  web/src/components/LogsTable.js
  web/src/components/OperationSetting.js
  web/src/pages/Setting/Operation/SettingsLog.js
Labels: trige: feature, size:L, lgtm

#113 feat(channel): add support for GitHub channel and model listing
  common/constants.go
  controller/channel.go
  relay/channel/github/constants.go
  relay/channel/openai/adaptor.go
  relay/constant/api_type.go
  relay/relay_adaptor.go
  web/src/constants/channel.constants.js
Labels: trige: feature, component: frontend, component: backend, size:L, lgtm

#121 fix(model): add Redis null check in redemption Redeem function
  model/redemption.go
Labels: size:S
