Repository Veloera/Veloera, pull requests merged in 2025-08, with the labels that each got.

#156 feat: Global Model Mapping
  controller/model.go
  controller/model_mapping.go
  controller/user.go
  examples/global_model_mapping_example.go
  main.go
  middleware/distributor.go
  model/ability.go
  model/global_model_mapping.go
  model/global_model_mapping_types.go
  relay/common/relay_info.go
  router/api-router.go
  service/global_model_mapping.go
  web/src/components/ModelSetting.js
  web/src/pages/Setting/Model/SettingModelMapping.js
Labels: trige: feature, size:XXL

#166 Update user.go
  model/user.go
Labels: component: backend, size:S

#182 feat: When adding or editing channels, add the function of clicking the added model to copy its name
  web/src/i18n/locales/en.json
  web/src/pages/Channel/EditChannel.js
Labels: trige: feature, component: frontend, size:XL

#185 feat(Channel): 添加模型重定向可视化编辑器组件
  web/src/i18n/locales/en.json
  web/src/pages/Channel/EditChannel.js
Labels: component: frontend, size:L, lgtm

#189 feat: 实现模型重定向中“键”自动映射到模型配置
  web/src/i18n/locales/en.json
  web/src/pages/Channel/EditChannel.js
Labels: trige: feature, component: frontend, size:L

#194 feat(table): 优化模型批量测试弹窗及相关操作
  web/src/components/ChannelsTable.js
  web/src/i18n/locales/en.json
Labels: trige: feature, component: frontend, size:XXL, lgtm
